# render.yaml
services:
  - type: web
    name: youtube-audio-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
